export interface PetTypeOption {
  id: string;
  label: string;
  icon: string;
}

export const PET_TYPE_OPTIONS: PetTypeOption[] = [
  { id: 'dogs', label: 'Dog', icon: 'pets' },
  { id: 'cats', label: 'Cat', icon: 'cat' },
  { id: 'rabbits', label: 'Rabbit', icon: 'cruelty_free' },
  { id: 'birds', label: 'Bird', icon: 'feather' },
  { id: 'hamsters', label: 'Hamster', icon: 'pest_control' },
  { id: 'other', label: 'Other', icon: 'category' },
];

export const BREEDS_BY_PET_TYPE: Record<string, string[]> = {
  dogs: [
    'Golden Retriever',
    'Labrador Retriever',
    'German Shepherd',
    'Indie / Indian Pariah Dog',
    'Beagle',
    'Shih Tzu',
    'Pug',
    'Poodle',
    'Rottweiler',
    'Siberian Husky',
    'Pomeranian',
    'Boxer',
    'Cocker Spaniel',
    'French Bulldog',
    'Dachshund',
    'Doberman Pinscher',
    'Great Dane',
    'Maltese',
    'Chihuahua',
    'American Bully',
    'Lhasa Apso',
    'Border Collie',
    'Australian Shepherd',
    'Chow Chow',
    'St. Bernard',
    'Other',
  ],
  cats: [
    'Persian',
    'Indie / Domestic Shorthair',
    'Siamese',
    'Maine Coon',
    'Bengal',
    'British Shorthair',
    'Ragdoll',
    'Sphynx',
    'Himalayan',
    'Scottish Fold',
    'Russian Blue',
    'Abyssinian',
    'Birman',
    'Turkish Angora',
    'Other',
  ],
  birds: [
    'Cockatiel',
    'Budgerigar / Budgie',
    'Lovebird',
    'African Grey Parrot',
    'Macaw',
    'Cockatoo',
    'Finch',
    'Canary',
    'Conure',
    'Indian Ringneck',
    'Parakeet',
    'Other',
  ],
  rabbits: [
    'Netherland Dwarf',
    'Holland Lop',
    'Mini Rex',
    'Lionhead',
    'Flemish Giant',
    'Angora',
    'Dutch Rabbit',
    'English Spot',
    'Other',
  ],
  hamsters: [
    'Syrian Hamster',
    'Dwarf Campbell Russian',
    'Dwarf Winter White',
    'Roborovski Dwarf',
    'Chinese Hamster',
    'Other',
  ],
  other: ['Other'],
};
